1. Import np

In [1]:
import numpy as np

2. Create an array of 10 zeros

In [4]:
array_zeros=np.zeros(10)
print(array)
array_zeros

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create an array of 10 ones

In [5]:
array_ones=np.ones(10)
print(array_ones)
array_ones

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
array_fives=np.ones(10)*5
print(array_fives)
array_fives

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
5. Create an array of integers from 10 to 50

In [14]:
array_10_50 = np.arange(10,50)
print(array_10_50)
array_10_50

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

6. Create an array of even integers from 10 to 50

In [15]:
array_10_50_even = np.arange(10, 50, 2)
print(array_10_50_even)
array_10_50_even


[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48]


array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48])

7. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
array_3_3 = np.arange(9).reshape(3,3)
print(array_3_3)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


8. Create a 3x3 identity matrix

In [20]:
array_identity=np.identity(3)
print(array_identity)
array_identity

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
9. Use numpy to randomly generate a number between 0 and 1

In [22]:
random_num = np.random.rand(1)
print(random_num)
random_num

[0.89976246]


array([0.89976246])